# Generated by Django 4.2.6 on 2024-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text='Required image or video', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
