# Generated by Django 4.2.6 on 2024-05-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventgallery_video_embed_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_to_date',
            field=models.DateField(null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Exhibition', 'Exhibition')], help_text='Event Type', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Event From Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_type', 'event_name')},
        ),
    ]
