# Generated by Django 4.2.6 on 2024-05-16 14:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_to_date_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[800, 800], upload_to='events/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[1200, 1200], upload_to='events/', verbose_name='Galery Image / Video Thumbnail'),
        ),
    ]
