# Generated by Django 4.2.6 on 2023-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
