# Generated by Django 4.2.6 on 2023-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_junk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
