# Generated by Django 4.2.6 on 2023-10-20 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0006_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
