# Generated by Django 4.2.7 on 2023-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_notes_added_by_alter_notes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='', max_length=255, null=True),
        ),
    ]
