# Generated by Django 4.2.7 on 2024-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_lead_address_remove_lead_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
