# Generated by Django 4.2.7 on 2024-01-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productgalery_image_title'),
        ('leads', '0009_lead_city_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadproducts', to='products.product'),
        ),
    ]
