# Generated by Django 4.2.7 on 2024-01-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_category_banner_video_embed_code_and_more'),
        ('leads', '0010_lead_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadcategories', to='app.category'),
        ),
        migrations.AddField(
            model_name='lead',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadsubcategories', to='app.subcategory'),
        ),
    ]
