# Generated by Django 4.2.7 on 2024-03-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_csrcategory_alter_csrreport_unique_together_and_more'),
        ('leads', '0011_lead_category_lead_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_junk',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_lost',
        ),
        migrations.AddField(
            model_name='lead',
            name='enquiry_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquirystatus', to='app.leadstatus'),
        ),
    ]
