# Generated by Django 4.2.7 on 2024-03-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_csrcategory_alter_csrreport_unique_together_and_more'),
        ('leads', '0012_remove_lead_is_deleted_remove_lead_is_junk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='enquiry_status',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquirystatus', to='app.leadstatus'),
        ),
    ]
