# Generated by Django 4.2.7 on 2024-03-27 13:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_lead_enquiry_status_lead_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True, unique=True)),
                ('email_body', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Template',
                'verbose_name_plural': 'Mail Templates',
            },
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_name', models.CharField(max_length=25, null=True)),
                ('email_to', models.EmailField(max_length=254, null=True)),
                ('email_cc', models.TextField(blank=True, help_text='Enter the email addresses you want to carbon copy (CC). Separate multiple addresses with commas.', null=True)),
                ('email_bcc', models.TextField(blank=True, help_text='Enter the email addresses you want to blind carbon copy (BCC). Separate multiple addresses with commas.', null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_template', models.ForeignKey(help_text='Select the email template you want to use for this email.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='leads.emailtemplate')),
            ],
        ),
    ]
