# Generated by Django 4.2.7 on 2024-03-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_emailtemplate_sendemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
