# Generated by Django 4.2.7 on 2024-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_sendemail_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
