# Generated by Django 4.2.7 on 2024-03-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_emailtemplate_template_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('user_agent', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='leads.sendemail')),
            ],
            options={
                'verbose_name': 'Mail Tracking',
                'verbose_name_plural': 'Mail Trackings',
            },
        ),
    ]
