# Generated by Django 4.2.7 on 2024-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_emailtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(help_text='Identifies which site sent the traffic, example:google', max_length=100, null=True)),
                ('utm_medium', models.CharField(help_text='Identifies what type of link was used, such as Pay-per-click or email, example:ppc', max_length=100, null=True)),
                ('utm_campaign', models.CharField(help_text='Identifies a specific product promotion or strategic campaign, example:spring_sale', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('utm_source', 'utm_medium', 'utm_campaign')},
            },
        ),
    ]
