# Generated by Django 4.2.7 on 2024-03-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('user_agent', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tracking', to='leads.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Tracking',
                'verbose_name_plural': 'Campaign Trackings',
            },
        ),
    ]
