# Generated by Django 4.2.7 on 2024-03-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_campaigntracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
