# Generated by Django 4.2.6 on 2023-11-29 06:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, null=True, unique=True)),
                ('qualifications', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('job_scope', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('experience', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('desired_skills', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
