# Generated by Django 4.2.6 on 2023-11-29 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('work_experience', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('current_location', models.CharField(max_length=50, null=True)),
                ('preferred_location', models.CharField(max_length=50, null=True)),
                ('resume', models.FileField(null=True, upload_to=jobs.models.get_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docs']), jobs.models.validate_file_size], verbose_name='Resume')),
                ('cover_letter', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.job')),
            ],
        ),
    ]
