# Generated by Django 4.2.6 on 2023-11-29 07:04

import django.core.validators
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='resume',
            field=models.FileField(null=True, upload_to=jobs.models.get_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docs', 'docx']), jobs.models.validate_file_size], verbose_name='Resume'),
        ),
    ]
