# Generated by Django 4.2.7 on 2024-01-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapply_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Department',
                'verbose_name_plural': 'Job Departments',
            },
        ),
        migrations.RenameField(
            model_name='job',
            old_name='desired_skills',
            new_name='desired_experience_skills',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='key_Responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='job',
            name='CTC_band',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='heading',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_departments', to='jobs.jobdepartment'),
        ),
    ]
