# Generated by Django 4.2.7 on 2024-01-24 11:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobdepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desired_experience_skills',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='key_Responsibilities',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
