# Generated by Django 4.2.7 on 2024-03-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_desired_experience_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Pending', max_length=20),
        ),
    ]
