# Generated by Django 4.2.7 on 2023-12-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
