# Generated by Django 4.2.7 on 2023-12-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_page_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
