# Generated by Django 4.2.7 on 2024-02-07 13:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_page_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image'),
        ),
    ]
