# Generated by Django 5.2.4 on 2025-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='sequence_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
