# Generated by Django 5.2.4 on 2025-08-04 10:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_leadership_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
