# Generated by Django 5.2.4 on 2025-08-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_leadership_description_alter_leadership_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipGroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_leadershipgimg', to='pages.page')),
            ],
        ),
    ]
