# Generated by Django 5.2.4 on 2025-08-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_leadershipgroupimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadershipgroupimage',
            options={'verbose_name': 'Leaders Group Image', 'verbose_name_plural': 'Leaders Group Image'},
        ),
    ]
