# Generated by Django 5.2.4 on 2025-08-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_leadershipgroupimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_video_iframe', models.TextField(blank=True, null=True)),
                ('who_we_are', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('who_we_are_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('our_vision', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('our_vision_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('our_mission', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('our_mission_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_aboutus', to='pages.page')),
            ],
            options={
                'verbose_name': 'About Us Image',
                'verbose_name_plural': 'About Us Images',
            },
        ),
    ]
