# Generated by Django 5.2.4 on 2025-08-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_ourbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_video_iframe', models.TextField(blank=True, null=True)),
                ('cultivating_creativity_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('cultivating_creativity_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cultivating_leadership_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('cultivating_leadership_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunities_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('opportunities_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('diversity_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('diversity_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_career', to='pages.page')),
            ],
            options={
                'verbose_name': 'Carrer Image',
                'verbose_name_plural': 'Carrer Images',
            },
        ),
    ]
