# Generated by Django 5.2.4 on 2025-08-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_carrerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('top_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('CSR_objective_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('CSR_objective_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_csr', to='pages.page')),
            ],
            options={
                'verbose_name': 'CSR Page Image',
                'verbose_name_plural': 'CSR Page Images',
            },
        ),
    ]
