# Generated by Django 5.2.4 on 2025-08-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_csrimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentsCertificatesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_video_iframe', models.TextField(blank=True, null=True)),
                ('quality_and_safety_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('quality_and_safety_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('our_patents_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('our_patents_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_patentscertificates', to='pages.page')),
            ],
            options={
                'verbose_name': 'Patents Certificates Image',
                'verbose_name_plural': 'Patents Certificates Images',
            },
        ),
    ]
