# Generated by Django 5.2.4 on 2025-08-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_patentscertificatesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDairyTechnologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_video_iframe', models.TextField(blank=True, null=True)),
                ('formulating_the_future_of_flavor_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('formulating_the_future_of_flavor_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('redefining_bakery_artistry_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('redefining_bakery_artistry_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('unleashing_taste_and_texture_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('unleashing_taste_and_texture_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('r_and_d_activities_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('r_and_d_activities_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_pfdt', to='pages.page')),
            ],
            options={
                'verbose_name': 'Food & Dairy Technology Image',
                'verbose_name_plural': 'Food & Dairy Technology Images',
            },
        ),
    ]
