# Generated by Django 5.2.4 on 2025-08-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_fooddairytechnologyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobialBiotechnologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_video_iframe', models.TextField(blank=True, null=True)),
                ('art_of_fermentation_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('art_of_fermentation_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('championing_progress_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('championing_progress_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('exploring_health_benefits_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('exploring_health_benefits_image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_mb', to='pages.page')),
            ],
            options={
                'verbose_name': 'Microbial Biotechnology Image',
                'verbose_name_plural': 'Microbial Biotechnology Images',
            },
        ),
    ]
