# Generated by Django 5.2.4 on 2025-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_microbialbiotechnologyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusimage',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrerimage',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooddairytechnologyimage',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microbialbiotechnologyimage',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patentscertificatesimage',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
