# Generated by Django 5.2.4 on 2025-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_aboutusimage_video_id_carrerimage_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourbrand',
            name='url_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
