# Generated by Django 4.2.6 on 2023-11-09 06:09

import app.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1600, 800], upload_to='category/', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_video',
            field=models.FileField(blank=True, null=True, upload_to='category/', validators=[app.models.validate_mp4_extension], verbose_name='Banner Video'),
        ),
    ]
