# Generated by Django 4.2.6 on 2023-11-09 06:30

import app.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_banner_image_category_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Required banner image or banner video', keep_meta=True, null=True, quality=85, scale=None, size=[1600, 800], upload_to='category/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_video',
            field=models.FileField(blank=True, help_text='Required banner image or banner video', null=True, upload_to='category/', validators=[app.models.validate_mp4_extension], verbose_name='Banner Video'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image')),
                ('list_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='category/', verbose_name='List Image')),
                ('banner_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 1600], upload_to='category/', verbose_name='Banner Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='category/', validators=[app.models.validate_mp4_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.category')),
            ],
        ),
    ]
