# Generated by Django 4.2.6 on 2023-11-09 10:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_tag_name_trustfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], help_text='Movement Direction', max_length=10)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='category/', verbose_name='Icon')),
                ('sequence_number', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
