# Generated by Django 4.2.6 on 2023-11-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='direction',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], help_text='Movement Direction', max_length=10),
        ),
    ]
