# Generated by Django 4.2.6 on 2023-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='direction',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], help_text='Icon movement direction', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('direction', 'name')},
        ),
    ]
