# Generated by Django 4.2.6 on 2023-11-09 13:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bakery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Required banner image or banner video', keep_meta=True, null=True, quality=95, scale=None, size=[1600, 800], upload_to='category/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='category/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 1600], upload_to='category/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='list_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='category/', verbose_name='List Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image'),
        ),
        migrations.AlterField(
            model_name='trustfactor',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='category/', verbose_name='Icon'),
        ),
    ]
