# Generated by Django 4.2.6 on 2023-11-10 11:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_category_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='right_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Right Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Left Description'),
        ),
    ]
