# Generated by Django 4.2.6 on 2023-11-10 11:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_category_right_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Intro Description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='List Description'),
        ),
    ]
