# Generated by Django 4.2.6 on 2023-11-10 11:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='product_section_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_section_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
