# Generated by Django 4.2.6 on 2023-11-10 11:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_subcategory_product_section_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product_section_description',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_section_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
