# Generated by Django 4.2.6 on 2023-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_subcategory_product_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory_sec_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_sec_short_des',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_sec_subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
