# Generated by Django 4.2.6 on 2023-11-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_category_subcategory_sec_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakery',
            options={'verbose_name': 'Bakery Location', 'verbose_name_plural': 'Bakery Locations'},
        ),
        migrations.AlterModelOptions(
            name='statics',
            options={'verbose_name': 'Legacy Number', 'verbose_name_plural': 'Legacy Numbers'},
        ),
    ]
