# Generated by Django 4.2.6 on 2023-11-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_bakery_options_alter_statics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
