# Generated by Django 4.2.6 on 2023-11-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_type_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_types_sub', to='app.type'),
        ),
    ]
