# Generated by Django 4.2.6 on 2023-11-22 08:13

import ckeditor_uploader.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_subtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bootom_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='bootom_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='category/'),
        ),
    ]
