# Generated by Django 4.2.7 on 2023-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_category_bootom_description_category_bootom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
