# Generated by Django 4.2.7 on 2023-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_csrhighlight_csrreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bakery',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bakery',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bakery',
            name='pin_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='bakery',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bakery',
            unique_together={('state', 'name', 'city', 'pin_code')},
        ),
    ]
