# Generated by Django 4.2.7 on 2023-12-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_bakery_unique_together_bakery_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakery',
            options={'verbose_name': 'Tropolite Dealer', 'verbose_name_plural': 'Tropolite Dealers'},
        ),
        migrations.AlterModelOptions(
            name='csrhighlight',
            options={'verbose_name': 'CSR Highlight', 'verbose_name_plural': 'CSR Highlights'},
        ),
        migrations.AlterModelOptions(
            name='csrreport',
            options={'verbose_name': 'CSR Report', 'verbose_name_plural': 'CSR Reports'},
        ),
    ]
