# Generated by Django 4.2.7 on 2024-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_video_embed_code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='video_embed_code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
