# Generated by Django 4.2.7 on 2024-01-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_category_banner_video_embed_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrreport',
            name='sequence_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
