# Generated by Django 4.2.7 on 2024-01-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_csrreport_sequence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsrCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('icon', models.FileField(upload_to='category/')),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CSR Category',
                'verbose_name_plural': 'CSR Categories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='csrreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='csrreport',
            name='csr_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csr_categories', to='app.csrcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='csrreport',
            unique_together={('csr_category', 'heading', 'report_date')},
        ),
    ]
