# Generated by Django 4.2.6 on 2023-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_meta_description_alter_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
