# Generated by Django 4.2.6 on 2023-10-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='written_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
