# Generated by Django 4.2.6 on 2023-11-21 07:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1600, 800], upload_to='blogs/', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='blogs/', verbose_name='List Image'),
        ),
    ]
