# Generated by Django 4.2.6 on 2023-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_video'),
        ('app', '0025_alter_category_options_alter_subcategory_options'),
        ('blogs', '0009_blog_banner_image_blog_meta_image_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
