# Generated by Django 4.2.7 on 2023-11-24 13:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_products_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1920, 1080], upload_to='blogs/', verbose_name='Banner Image'),
        ),
    ]
