# Generated by Django 4.2.7 on 2023-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blog_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
