# Generated by Django 4.2.7 on 2023-11-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blog_intro_description_blog_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='intro_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
