# Generated by Django 4.2.7 on 2024-02-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_blog_heading_alter_blog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
