# Generated by Django 4.2.7 on 2024-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_blog_canonical_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='canonical_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
