# Generated by Django 4.2.7 on 2024-03-20 11:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_blog_canonical_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='intro_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
