# Generated by Django 4.2.6 on 2023-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leadsource_leadstatus'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
