# Generated by Django 4.2.6 on 2023-10-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_shelf_life'),
        ('recipes', '0002_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
