# Generated by Django 4.2.6 on 2023-11-09 13:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='recipes/', verbose_name='List Image'),
        ),
    ]
