# Generated by Django 4.2.6 on 2023-11-15 07:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_meta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='how_to_make_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Product Short Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='right_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Right Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Left Description'),
        ),
    ]
