# Generated by Django 4.2.6 on 2023-11-15 07:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_how_to_make_it_recipe_right_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bottom_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Bottom Description'),
        ),
    ]
