# Generated by Django 4.2.6 on 2023-11-15 07:11

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_bottom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='recipes/', verbose_name='Galery Image')),
                ('description', models.TextField(max_length=500, null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipeprocess', to='recipes.recipe')),
            ],
        ),
    ]
