# Generated by Django 4.2.6 on 2023-11-21 06:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1600, 800], upload_to='recipes/', verbose_name='Banner Image'),
        ),
    ]
