# Generated by Django 4.2.6 on 2023-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
