# Generated by Django 4.2.6 on 2023-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
