# Generated by Django 4.2.6 on 2023-11-21 10:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_how_to_make_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='how_to_make_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Product Short Description'),
        ),
    ]
