# Generated by Django 4.2.7 on 2023-11-24 13:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_how_to_make_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1920, 1080], upload_to='recipes/', verbose_name='Banner Image'),
        ),
    ]
