# Generated by Django 4.2.7 on 2023-11-28 08:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bottom_description_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='bottom_right_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Bottom Right Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='bottom_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Bottom Left Description'),
        ),
    ]
