# Generated by Django 4.2.7 on 2023-12-06 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipe_bottom_description_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Left Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Left Description'),
        ),
    ]
