# Generated by Django 4.2.7 on 2023-12-06 08:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_process_description_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description'),
        ),
    ]
