# Generated by Django 4.2.7 on 2024-02-05 07:21

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productgalery_image_title'),
        ('recipes', '0020_alter_recipe_heading_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFlavourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[800, 800], upload_to='products/', verbose_name='List Image')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipeproduct', to='products.product')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipefl', to='recipes.recipe')),
            ],
        ),
    ]
