# Generated by Django 4.2.7 on 2024-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_productflavourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
