# Generated by Django 4.2.7 on 2024-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_recipe_cook_time_alter_recipe_written_by_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
