# Generated by Django 4.2.6 on 2023-10-23 11:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='Shelf Life (Month)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='products/', verbose_name='List Image'),
        ),
    ]
