# Generated by Django 4.2.6 on 2023-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shelf_life_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_life_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
