# Generated by Django 4.2.6 on 2023-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_shelf_life_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.IntegerField(blank=True, help_text='Months', null=True, verbose_name='Shelf Life'),
        ),
    ]
