# Generated by Django 4.2.6 on 2023-11-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shelf Life'),
        ),
    ]
