# Generated by Django 4.2.6 on 2023-11-09 08:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_shelf_life_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientworks', to='products.product')),
            ],
        ),
    ]
