# Generated by Django 4.2.6 on 2023-11-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productattributes', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributes',
            unique_together={('product', 'heading')},
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, null=True, unique=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsize', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
