# Generated by Django 4.2.6 on 2023-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_banner_image_and_more'),
        ('products', '0008_alter_productattributes_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
