# Generated by Django 4.2.6 on 2023-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_temp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage Temp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shelf Life'),
        ),
    ]
