# Generated by Django 4.2.6 on 2023-11-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_storage_temp_alter_product_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, null=True, unique=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productcolor', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'color')},
            },
        ),
    ]
