# Generated by Django 4.2.6 on 2023-11-09 12:27

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productsize_size_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='products/', verbose_name='Galery Image')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productgalery', to='products.product')),
            ],
        ),
    ]
