# Generated by Django 4.2.6 on 2023-11-09 13:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_image_alter_productgalery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image'),
        ),
    ]
