# Generated by Django 4.2.6 on 2023-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_meta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color_code',
            field=models.CharField(blank=True, help_text='Ex #FFFFFF', max_length=7, null=True, verbose_name='Background Color Code'),
        ),
    ]
