# Generated by Django 4.2.6 on 2023-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_background_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='background_color_code',
            field=models.CharField(blank=True, help_text='Ex - #FFFFFF', max_length=7, null=True, verbose_name='Background Color Code'),
        ),
    ]
