# Generated by Django 4.2.6 on 2023-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_background_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(help_text='Short description on listing', max_length=500, null=True),
        ),
    ]
