# Generated by Django 4.2.6 on 2023-11-15 07:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_sub_title_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='used_directions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
