# Generated by Django 4.2.6 on 2023-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_used_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sequence_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
