# Generated by Django 4.2.6 on 2023-11-16 05:54

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_mp4_extension]),
        ),
    ]
