# Generated by Django 4.2.6 on 2023-11-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_subtype_type'),
        ('products', '0021_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psub_type', to='app.subtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptype', to='app.type'),
        ),
    ]
