# Generated by Django 4.2.6 on 2023-11-22 09:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_sub_type_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1000, 1000], upload_to='products/', verbose_name='Banner Image'),
        ),
    ]
