# Generated by Django 4.2.6 on 2023-11-22 09:57

from django.db import migrations, models
import django_resized.forms
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[1000, 1000], upload_to='products/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_mp4_extension], verbose_name='Banner Video'),
        ),
    ]
