# Generated by Django 4.2.7 on 2023-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_banner_image_alter_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_life_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_section_subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_section_temp_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
