# Generated by Django 4.2.7 on 2023-12-14 13:25

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_shelf_life_section_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Product Flavour', 'verbose_name_plural': 'Product Flavours'},
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='color',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'name')},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[800, 800], upload_to='products/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='sub_heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[1000, 1000], upload_to='products/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[800, 800], upload_to='products/', verbose_name='List Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[800, 800], upload_to='metaimage/', verbose_name='Meta Image'),
        ),
        migrations.AlterField(
            model_name='productgalery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=98, scale=None, size=[800, 800], upload_to='products/', verbose_name='Galery Image'),
        ),
    ]
