# Generated by Django 4.2.7 on 2023-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productcolor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heading_for_flavour_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
