# Generated by Django 4.2.7 on 2023-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_heading_for_flavour_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tild_list_image',
            field=models.BooleanField(default=False),
        ),
    ]
