# Generated by Django 4.2.7 on 2023-12-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_is_tild_list_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'name', 'sub_heading')},
        ),
    ]
