# Generated by Django 4.2.7 on 2023-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_productcolor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
