# Generated by Django 4.2.7 on 2024-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_productcolor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_embed_code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
