# Generated by Django 4.2.7 on 2024-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_video_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgalery',
            name='image_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
