# Generated by Django 4.2.7 on 2024-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productgalery_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_now_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
